- name: devops course information
  hosts: localhost
  vars:
    course: "DevOps"
    duration: 120
    topics:
      - Ansible
      - Docker
      - Kubernetes
      - Terraform
    live: true
    tools:
      ci: Jenkins
      cm: Ansible
      cloud: aws
  tasks:
    - name: display course information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ course }} for {{ duration }} days. The topics covered are {{ topics }}. Is this a live course? {{ live }}. The tools used are CI: {{ tools.ci }}, CM: {{ tools.cm }}, Cloud: {{ tools.cloud }}."