- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check if the user exists
    ansible.builtin.command: id expense
    # USER is a variable that gets output from the above command
    register: USER
    ignore_errors: True
    
  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"