- name: demo on filters
  hosts: web
  become: yes
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
  
  - name: convert to uppercase
    vars: 
      greeting: "Hello John"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
  
  - name: convert to uppercase
    vars: 
      greeting: "Hello John"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: getting unique values
    vars:
      numbers: [1,4,6,2,5,84,6,2]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: getting min and max
    vars:
      numbers: [1,4,6,2,5,84,6,2]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"