- name: command vs shell
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: command vs shell
     ansible.builtin.shell: ls -ltr > /tmp/output.txt
     #.shell will only work in the above line because command cannot perform redirects aor any complex shell commands
     #shell module logs into the server and executes the command 
     #command module only issues the command
     #command module doesn't log into the server hence it is more secure

   - name: check the process
     ansible.builtin.command: ps -ef | grep ssh
     register: output
