- name: command vs shell
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: command vs shell
     ansible.builtin.shell: ls -ltr > /tmp/output.txt
     #.shell will only work in the above line because command cannot perform redirects aor any complex shell commands