- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-08d8e94e48bab0c56
    sg_id: sg-049b405284d2ff233
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
  tasks:
   - name: creating ec2 instance using boto3
     amazon.aws.ec2_instance:
       name: "{{ item }}"
       vpc_subnet_id: "{{subnet_id}}"
       instance_type: t3.micro
       security_group: "{{ sg_id }}"
       image_id: "{{ ami_id }}"
     loop: "{{ instances}}"
     register: ec2_instances

   - name: print the output
     ansible.builtin.debug:
       msg: "{{ ec2_instances.private_ip_address}}"